from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(757, 485)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(500, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(33, 110, 241, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_addname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_addname.setObjectName("line_addname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_addname)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comBox1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comBox1.setObjectName("comBox1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comBox1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comBox2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comBox2.setObjectName("comBox2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comBox2)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainText1 = QtWidgets.QPlainTextEdit(Form)
        self.plainText1.setGeometry(QtCore.QRect(100, 210, 171, 71))
        self.plainText1.setObjectName("plainText1")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 330, 241, 80))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.line_addprice = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_addprice.setObjectName("line_addprice")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_addprice)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.line_addvolume = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_addvolume.setObjectName("line_addvolume")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_addvolume)
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(100, 430, 91, 31))
        self.btn_add.setObjectName("btn_add")
        self.line_id = QtWidgets.QLineEdit(Form)
        self.line_id.setGeometry(QtCore.QRect(442, 90, 121, 20))
        self.line_id.setObjectName("line_id")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 90, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(390, 340, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.plainText2 = QtWidgets.QPlainTextEdit(Form)
        self.plainText2.setGeometry(QtCore.QRect(460, 340, 231, 71))
        self.plainText2.setObjectName("plainText2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(400, 90, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btn_red = QtWidgets.QPushButton(Form)
        self.btn_red.setGeometry(QtCore.QRect(500, 430, 91, 31))
        self.btn_red.setObjectName("btn_red")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(320, 0, 21, 471))
        self.frame.setStyleSheet("background-color: rgb(255, 254, 233);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 751, 16))
        self.frame_2.setStyleSheet("background-color: rgb(255, 254, 233);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(730, 0, 21, 471))
        self.frame_3.setStyleSheet("background-color: rgb(255, 254, 233);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(0, 470, 751, 16))
        self.frame_4.setStyleSheet("background-color: rgb(255, 254, 233);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 16, 471))
        self.frame_5.setStyleSheet("background-color: rgb(255, 254, 233);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(400, 260, 281, 61))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.comBox3 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comBox3.setObjectName("comBox3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comBox3)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.formLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(400, 150, 281, 80))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.line_redname = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.line_redname.setObjectName("line_redname")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_redname)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.line_redprice = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.line_redprice.setObjectName("line_redprice")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_redprice)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.line_redvolume = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.line_redvolume.setObjectName("line_redvolume")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_redvolume)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Добавить"))
        self.label_2.setText(_translate("Form", "Изменить"))
        self.label_3.setText(_translate("Form", "Имя:"))
        self.label_4.setText(_translate("Form", "Прожарка:"))
        self.label_5.setText(_translate("Form", "Зёрна/молотый:"))
        self.label_6.setText(_translate("Form", "Вкус:"))
        self.label_7.setText(_translate("Form", "Цена:"))
        self.label_8.setText(_translate("Form", "Объём:"))
        self.btn_add.setText(_translate("Form", "Добавить"))
        self.pushButton_2.setText(_translate("Form", "Выбрать"))
        self.label_9.setText(_translate("Form", "Вкус:"))
        self.label_10.setText(_translate("Form", "ID:"))
        self.btn_red.setText(_translate("Form", "Изменить"))
        self.label_12.setText(_translate("Form", "Молотый/в зёрнах:"))
        self.label_11.setText(_translate("Form", "Степень прожарки:"))
        self.label_14.setText(_translate("Form", "Цена:"))
        self.label_15.setText(_translate("Form", "Объём:"))
        self.label_13.setText(_translate("Form", "Название:"))
